### PR TITLE
Minicart design

### PR DESCRIPTION
**Pull request by cramirez451**

### CODE REVIEW

**Comment by mirandaposthumus** [comment]
@cramirez451 with this code you would not be displaying the cart button when the checkout component doesn't exist. Cart button always needs to show.

**Comment by crhistian26** [comment]
I'm not seeing that?
<div ng-if="!minicart.checkForCheckout()">
                        <button class="btn btn-sm btn-info btn-block" ngclick="minicart.goToCart()">Cart</button>
</div>

Is showing cart button when the minicart doesn't exist.

**Comment by cramirez451** [comment]
I'm not seeing that?
```
<div ng-if="!minicart.checkForCheckout()">
<button class="btn btn-sm btn-info btn-block" ng-click="minicart.goToCart()">Cart</button>
</div>
```

**Comment by mirandaposthumus** [comment]
@cramirez451 ng-if="!minicart.checkForCheckout()" is a function that checks to see if the checkout component exists, since there is a bang, it is saying, if the checkout component doesn't exist, then show this cart button. The cart button always needs to be displayed, regardless of if the checkout component exists

**Pull request closed without merging**
